### ISSUE TITLE
build on latest ubuntu fail

### ISSUE THREAD

**Issue by sphaero** [zeromq/zeromq4-1#15]
pulled latest:
```
git clone https://github.com/zeromq/zeromq4-1.git
./autogen.sh 
./configure --without-libsodium
make -j6 && make check
```
```
PASS: test_timeo
./config/test-driver: line 107: 25920 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: test_filter_ipc
PASS: test_fork
PASS: test_abstract_ipc
make[4]: Entering directory '/home/people/arnaud/src/zeromq4-1'
Making all in doc
make[5]: Entering directory '/home/people/arnaud/src/zeromq4-1/doc'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/people/arnaud/src/zeromq4-1/doc'
make[5]: Entering directory '/home/people/arnaud/src/zeromq4-1'
make[5]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
make[4]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
============================================================================
Testsuite summary for zeromq 4.1.1
============================================================================
# TOTAL: 58
# PASS:  57
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to zeromq-dev@lists.zeromq.org
============================================================================
Makefile:3187: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
Makefile:3293: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
Makefile:3981: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
Makefile:3073: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
```
$ more ./test-suite.log 
====================================
   zeromq 4.1.1: ./test-suite.log
====================================

# TOTAL: 58
# PASS:  57
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_filter_ipc
=====================

lt-test_filter_ipc: tests/testutil.hpp:68: void bounce(void*, void*): Assertion `rc == 32' failed.
```

**Comment by jemc** [comment]
Is this a singluar failure or is it consistent?

**Comment by sphaero** [comment]
```
$ make clean && make -j6 && make check
...
PASS: test_timeo
./config/test-driver: line 107:  5423 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: test_filter_ipc
PASS: test_fork
PASS: test_abstract_ipc
make[4]: Entering directory '/home/people/arnaud/src/zeromq4-1'
Making all in doc
make[5]: Entering directory '/home/people/arnaud/src/zeromq4-1/doc'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/people/arnaud/src/zeromq4-1/doc'
make[5]: Entering directory '/home/people/arnaud/src/zeromq4-1'
make[5]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
make[4]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
============================================================================
Testsuite summary for zeromq 4.1.1
============================================================================
# TOTAL: 58
# PASS:  57
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to zeromq-dev@lists.zeromq.org
============================================================================
Makefile:3187: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
Makefile:3293: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
Makefile:3981: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/people/arnaud/src/zeromq4-1'
Makefile:3073: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
every make check fails exactly the same

**Comment by rodgert** [comment]
I just checked this against Ubuntu 14.04 and all tests pass (both with and
--without-libsodium). I assume by 'latest Ubuntu' you mean 14.10?

from the tests subdirectory, can you -

libtool --mode=execute gdb test_filter_ipc

At the gdb prompt type 'r'

When it segfaults, type 'bt' and paste the stack trace into a message?

**Comment by sphaero** [comment]
Completely forgot about this issue until I tried again today on a clean ubuntu 15.04 machine. Same issue still, here's the stacktrace:
```
$ libtool --mode=execute gdb ../test_filter_ipc
GNU gdb (Ubuntu 7.9-1ubuntu1) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/people/arnaud/src/zeromq4-1/.libs/lt-test_filter_ipc...done.
(gdb) r
Starting program: /home/people/arnaud/src/zeromq4-1/.libs/lt-test_filter_ipc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
12345678ABCDEFGH12345678abcdefgh0o` : rc=32
12345678ABCDEFGH12345678abcdefgh�B` : rc=32
[New Thread 0x7ffff60fd700 (LWP 16312)]
[New Thread 0x7ffff68fe700 (LWP 16311)]
[Thread 0x7ffff60fd700 (LWP 16312) exited]
[Thread 0x7ffff68fe700 (LWP 16311) exited]
12345678ABCDEFGH12345678abcdefgh�p` : rc=32
0x` : rc=-1
lt-test_filter_ipc: tests/testutil.hpp:69: void bounce(void*, void*): Assertion `rc == 32' failed.
[New Thread 0x7ffff60fd700 (LWP 16316)]
[New Thread 0x7ffff68fe700 (LWP 16315)]

Program received signal SIGABRT, Aborted.
0x00007ffff75bb267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff75bb267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff75bceca in __GI_abort () at abort.c:89
#2  0x00007ffff75b403d in __assert_fail_base (fmt=0x7ffff7716028 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x402792 "rc == 32", file=file@entry=0x4027bf "tests/testutil.hpp", line=line@entry=69, 
    function=function@entry=0x4029b0 <bounce(void*, void*)::__PRETTY_FUNCTION__> "void bounce(void*, void*)") at assert.c:92
#3  0x00007ffff75b40f2 in __GI___assert_fail (assertion=0x402792 "rc == 32", file=0x4027bf "tests/testutil.hpp", line=69, function=0x4029b0 <bounce(void*, void*)::__PRETTY_FUNCTION__> "void bounce(void*, void*)") at assert.c:101
#4  0x000000000040177e in bounce (server=server@entry=0x6070d0, client=client@entry=0x607830) at tests/testutil.hpp:69
#5  0x0000000000402108 in run_test<unsigned int> (opt=opt@entry=60, optval=optval@entry=4, bounce_test=bounce_test@entry=1, expected_error=0) at tests/test_filter_ipc.cpp:102
#6  0x0000000000400fd9 in main () at tests/test_filter_ipc.cpp:141
```

**Comment by sphaero** [comment]
ow btw the string outputs are mine. I just added a printf("%s : rc=%d\n", buffer, rc); to the test

**Comment by rodgert** [comment]
I just received a new dev machine with 15.04, I will try to reproduce.

**Comment by rodgert** [comment]
I just built the latest libzmq head version, as well as 4-1 on 15.04
(gcc4.9.2) no test errors.

**Comment by hintjens** [comment]
Closing.
